### ISSUE TITLE
Docs in folders

### ISSUE THREAD

**Issue by Ponamarev** [minaev-aa/pygame_sem_project#12]
Wrote a README in the engine. Check that the description of your files is correct.
Write documentation for the other folders.

**Comment by Kolin48** [comment]
problems with encoding.
![capture_20201209163603712](https://user-images.githubusercontent.com/71868467/101637820-4d0ccd00-3a3e-11eb-9ed4-15039de5f99d.jpg)

**Comment by minaev-aa** [comment]
fixed

**Comment by Ponamarev** [comment]
@Dobrovenskis , please add the documentation to the file active_walls.py in the engine folder.
