### ISSUE TITLE
Spawn bag

### ISSUE THREAD

**Issue by Ponamarev** [minaev-aa/pygame_sem_project#7]
One of players is spawned in textures.

**Comment by Ponamarev** [comment]
![image](https://user-images.githubusercontent.com/71901075/101283772-459eb700-37e5-11eb-90d5-e4acb0b0f050.png)

**Comment by Ponamarev** [comment]
![image](https://user-images.githubusercontent.com/71901075/101284030-aa0e4600-37e6-11eb-9a58-2431e6d2fb01.png)
![image](https://user-images.githubusercontent.com/71901075/101284037-b6929e80-37e6-11eb-8c17-fe7ea26c4fc8.png)

**Comment by minaev-aa** [comment]
fix
