### ISSUE TITLE
Disappearing textures

### ISSUE THREAD

**Issue by minaev-aa** [minaev-aa/pygame_sem_project#8]
Fix bug. If you go to the outer corner of the corridor, the texture disappears.

![4W_hREVU0CI](https://user-images.githubusercontent.com/71834110/101284304-5d2f6d00-37f0-11eb-9f33-7b188c7c8078.jpg)
See on map

**Comment by Ponamarev** [comment]
Fixed. Now you can't see through the walls using corner of corridor.
